# Generated by Django 3.1.4 on 2021-10-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='description',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
